@startuml
class GameManager {
    + CharacterCamera : GameObject
    - _activeCharacter : GameObject

    + CheckpointActivated(player : Player, checkpointPosition : Vector3) : void

    + LoadGameScene() : void
    + QuitGame() : void

    + ResetGameData() : void
}

class GameBar {

    + RestartButton : GameObject
    + KiwiHUDSections : List<GameObject>

    + KiwiSprite : Sprite
    + SelectedKiwiSprite : Sprite
    + UsedKiwiSprite : Sprite

    + RestartButtonSprite : Sprite
    + SelectedRestartButtonSprite : Sprite

    - _liLypadsCount : int
    - _currentKiwiIndex : int

    - ResetOneKiwiSection() : void
    - ResetAllKiwiSections() : void
    - ResetRestartButton() : void

    - HandleOnKiwiCollected(type : Kiwi.LilyPadType) : void
    - HandleCheckpointActivated() : void
    - HandleParryRingCollected() : void
    - HandlePlayerReset() : void
    - HandlePlayerJump() : void
}


class Player {

    # MoveSpeed : float
    # MaxSpeedMultiplier : float
    # Acceleration : float
    # Deceleration : float

    # JumpForce : float
    # MaximumJumps : int
    # AirJumpReduction : float

    # ParryWindow : float
    # ParryCooldown : float
    # ParryJumpMultiplier : float

    + PlayerIsParrying : bool

    + PlayerSendToSpawnPoint() : void
    + PerformJump(force : float) : void

    # Move(context : CallbackContext) : void
    # IsGrounded() : bool

    # HandleMovement() : void
    # HandleJump() : void

    - Jump(context : CallbackContext) : void
    - JumpCancelled(context : CallbackContext) : void
    - CalculateAirJumpDivisor() : float
    - EnableJumpCutIgnore(duration : float) : void
    - Restart(context : CallbackContext) : void

    - CoyoteTimeCoroutine() : IEnumerator
    - KiwiTimeCoroutine() : IEnumerator
    - ParryWindowCoroutine() : IEnumerator
    - ParryCooldownCoroutine() : IEnumerator
    - JumpCooldownCoroutine() : IEnumerator

    - HandleSuccessfulParry(parryable : Parryable) : void
    - HandleKiwiCollected(type : LilyPadType) : void
    - HandleCheckpointActivated() : void
    - HandleFlyCollected() : void
}


class NewGameGreen {
    + OnNewGameButtonPressed() : void
}

class ContinueButton {
    + OnContinueButtonPressed() : void
}

class QuitButton {
    + OnQuitButtonPressed() : void
}

GameManager --> GameBar
GameManager --> Player

GameBar --> Player


@enduml